import 'package:flutter/material.dart';


class ProductJson{

  //add category json fields
  static final category = {
    "id" : "1",
    "category_name" : "name",
    "category_image" : "da",
    "create_at" : "adsfsd"
  };


  //add category json fields
  static final subCategory = {
    "id" : "1",
    "category" : "name",
    "sub_category" : "da",
    "create_at" : "adsfsd"
  };


  //variant
  static final variantsJson = {
    "id" : "1",
    "name": "name",
    "variants" : [],
    "create_at" : "asdfsd"
  };


  //products controllers
  static final productsJson = {
    "name" : "Product Name",
    "short_description" : "",
    "long_description" :"",
    "products_tags" : [],
    "images" : [],
    "regular_price" : "",
    "whole_price" : "",
    "selling_price" : "",
    "discount_price" : "",
    "category's" : {
      "id" : "1",
      "category_name" : "name",
      "category_image" : "da",
      "create_at" : "adsfsd"
    },
    "variants" : [
      {
        "name" : "xl",
        "prince" : "princ"
      },
      {
        "name" : "xl",
        "prince" : "princ"
      }
    ],
    "status" : "10",
    "is_stock" : "",
    "product_type" : "KG",
    "create_at" : ""

  };


  static final productTypeList = [
    "KG (€ / Kg)",
    "G (€ / G)",
    "MG (€ / MG)",
    "L (€ / L)",
    "ML (€ / ML)",
    "U (€ / U)",
    "CM (€ / CM)",
    "MM (€ / MM)",
    "M (€ / M)",
    // "Liquid",
    // "Solid",
    // "Gas",
    // "Powder",
    // "Gel",
    // "Paste",
    // "Crystals",
    // "Granules",
    // "Pellets",
    // "Packet",
    // "Bottle",
    // "Jar",
    // "Can",
    // "Box",
    // "Bag",
    // "Tube",
    // "Sachet",
    // "Carton",
    // "Barrel",
    // "Drum",
    // "Container",
    // "Blister Pack",
    // "Strip Pack",
    // "Pouch"
  ];

  //country List
  static final countries=[
    "Bangladesh",
    "India",
    "Pakistan",

  ];

  //TVA List
  static final tvas=["0","5.5","20"];

  //short description
  static final descriptionList=[
    "Le Kilo",
    "La Pièce",
    "Le Litre",
    "Le Colis",
    "La Palette",
    "---------",
    "La Barquette",
    "Le Bocal",
    "La Boite",
    "La Botte",
    "La Bouteille",
    "Le Filet",
    "Le Lot",
    "Le Pack",
    "Le Paquet",
    "La Portion",
    "Le Pot",
    "Le Sac",
    "Le Sachet",

  ];



  static final allCountry = [
    "Afghanistan",
    "Îles Åland",
    "Albanie",
    "Algérie",
    "Samoa américaines",
    "Andorre",
    "Angola",
    "Anguilla",
    "Antarctique",
    "Antigua-et-Barbuda",
    "Argentine",
    "Arménie",
    "Aruba",
    "Australie",
    "Autriche",
    "Azerbaïdjan",
    "Bahamas",
    "Bahreïn",
    "Bangladesh",
    "Barbade",
    "Biélorussie",
    "Belgique",
    "Belize",
    "Bénin",
    "Bermudes",
    "Bhoutan",
    "Bolivie",
    "Bosnie-Herzégovine",
    "Botswana",
    "Île Bouvet",
    "Brésil",
    "Territoire britannique de l'océan Indien",
    "Brunéi Darussalam",
    "Bulgarie",
    "Burkina Faso",
    "Burundi",
    "Cambodge",
    "Cameroun",
    "Canada",
    "Cap-Vert",
    "Îles Caïmans",
    "République centrafricaine",
    "Tchad",
    "Chili",
    "Chine",
    "Île Christmas",
    "Îles Cocos (Keeling)",
    "Colombie",
    "Comores",
    "Congo",
    "République démocratique du Congo",
    "Îles Cook",
    "Costa Rica",
    "Côte d'Ivoire",
    "Croatie",
    "Cuba",
    "Chypre",
    "République tchèque",
    "Danemark",
    "Djibouti",
    "Dominique",
    "République dominicaine",
    "Équateur",
    "Égypte",
    "Salvador",
    "Guinée équatoriale",
    "Érythrée",
    "Estonie",
    "Éthiopie",
    "Îles Malouines (Falkland)",
    "Îles Féroé",
    "Fidji",
    "Finlande",
    "France",
    "Guyane française",
    "Polynésie française",
    "Terres australes françaises",
    "Gabon",
    "Gambie",
    "Géorgie",
    "Allemagne",
    "Ghana",
    "Gibraltar",
    "Grèce",
    "Groenland",
    "Grenade",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernesey",
    "Guinée",
    "Guinée-Bissau",
    "Guyana",
    "Haïti",
    "Îles Heard et McDonald",
    "Saint-Siège (État de la Cité du Vatican)",
    "Honduras",
    "Hong Kong",
    "Hongrie",
    "Islande",
    "Inde",
    "Indonésie",
    "Iran, République islamique d'",
    "Irak",
    "Irlande",
    "Île de Man",
    "Israël",
    "Italie",
    "Jamaïque",
    "Japon",
    "Jersey",
    "Jordanie",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Corée, République populaire démocratique de",
    "Corée, République de",
    "Koweït",
    "Kirghizistan",
    "Lao, République démocratique populaire",
    "Lettonie",
    "Liban",
    "Lesotho",
    "Libéria",
    "Libye",
    "Liechtenstein",
    "Lituanie",
    "Luxembourg",
    "Macao",
    "Macédoine, Ex-République yougoslave de",
    "Madagascar",
    "Malawi",
    "Malaisie",
    "Maldives",
    "Mali",
    "Malte",
    "Îles Marshall",
    "Martinique",
    "Mauritanie",
    "Maurice",
    "Mayotte",
    "Mexique",
    "Micronésie, États fédérés de",
    "Moldavie, République de",
    "Monaco",
    "Mongolie",
    "Montserrat",
    "Maroc",
    "Mozambique",
    "Myanmar",
    "Namibie",
    "Nauru",
    "Népal",
    "Pays-Bas",
    "Antilles néerlandaises",
    "Nouvelle-Calédonie",
    "Nouvelle-Zélande",
    "Nicaragua",
    "Niger",
    "Nigéria",
    "Niue",
    "Île Norfolk",
    "Îles Mariannes du Nord",
    "Norvège",
    "Oman",
    "Pakistan",
    "Palaos",
    "Territoire palestinien, occupé",
    "Panama",
    "Papouasie-Nouvelle-Guinée",
    "Paraguay",
    "Pérou",
    "Philippines",
    "Pitcairn",
    "Pologne",
    "Portugal",
    "Porto Rico",
    "Qatar",
    "Réunion",
    "Roumanie",
    "Fédération de Russie",
    "Rwanda",
    "Sainte-Hélène",
    "Saint-Kitts-et-Nevis",
    "Sainte-Lucie",
    "Saint-Pierre-et-Miquelon",
    "Saint-Vincent-et-les-Grenadines",
    "Samoa",
    "Saint-Marin",
    "Sao Tomé-et-Principe",
    "Arabie Saoudite",
    "Sénégal",
    "Serbie-et-Monténégro",
    "Seychelles",
    "Sierra Leone",
    "Singapour",
    "Slovaquie",
    "Slovénie",
    "Îles Salomon",
    "Somalie",
    "Afrique du Sud",
    "Géorgie du Sud-et-les Îles Sandwich du Sud",
    "Espagne",
    "Sri Lanka",
    "Soudan",
    "Suriname",
    "Svalbard et Île Jan Mayen",
    "Swaziland",
    "Suède",
    "Suisse",
    "République arabe syrienne",
    "Taïwan, Province de Chine",
    "Tadjikistan",
    "Tanzanie, République-Unie de",
    "Thaïlande",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinité-et-Tobago",
    "Tunisie",
    "Turquie",
    "Turkménistan",
    "Îles Turques-et-Caïques",
    "Tuvalu",
    "Ouganda",
    "Ukraine",
    "Émirats Arabes Unis",
    "Royaume-Uni",
    "États-Unis",
    "Îles mineures éloignées des États-Unis",
    "Uruguay",
    "Ouzbékistan",
    "Vanuatu",
    "Venezuela",
    "Viet Nam",
    "Îles Vierges britanniques",
    "Îles Vierges des États-Unis",
    "Wallis-et-Futuna",
    "Sahara occidental",
    "Yémen",
    "Zambie",
    "Zimbabwe"
  ];

  //user Role
  static final userRole=[
    "Super Admin",
    "Admin",
    "Buyer",
    "Preparer",
    "Deliverer",
    "Accounting",
    "Sales",
  ];

  static final orderStatus=[
    "En preparación",
    "Livree",
    "Annulee",
  ];

  static final deliveryBoy = [
    "Jean Dupont",
    "Marie Rousseau",
    "Paul Martin",

  ];

  static final payment = [
    "Prelevement SEPA",
    "Virement",
    "Carte Bancaire",

  ];

  static final status = [
    "En Attente",
    "Actif",
    "Inactif",
    "Blacklist",

  ];



}